---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
  - get
- apiGroups:
  - cfy.cz
  resources:
  - vaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cfy.cz
  resources:
  - vaultsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - cfy.cz
  resources:
  - vaultsecrets/status
  verbs:
  - get
  - patch
  - update
