apiVersion: v1
kind: Secret
metadata:
  name: controller-manager-token
  annotations:
    kubernetes.io/service-account.name: vault-secret-injector-controller-manager
type: kubernetes.io/service-account-token