apiVersion: cfy.cz/v1
kind: VaultSecret
metadata:
  labels:
    app.kubernetes.io/name: vault-secret-injector
    app.kubernetes.io/managed-by: kustomize
  name: vaultsecret-sample
spec:
  stringData:
    secret-key: secret/data/myapp/config#password
