apiVersion: cfy.cz/v1
kind: VaultSecret
metadata:
  annotations:
    vault.hashicorp.com/refresh-interval: 10s
    vault.hashicorp.com/path: test
    vault.hashicorp.com/service-account: new-sa
  labels:
    app.kubernetes.io/name: vault-secret-injector
    app.kubernetes.io/managed-by: kustomize
  name: vaultsecret-sample
  namespace: test
spec:
  type: Opaque
  stringData:
    SECRET_KEY: test@USERNAME
  rolloutObjectsRef:
    - apiVersion: apps/v1
      kind: Deployment
      name: my-deployment
