apiVersion: cfy.cz/v1
kind: VaultSecret
metadata:
  annotations:
    vault.hashicorp.com/mount: kv-test
    vault.hashicorp.com/path: test
    vault.hashicorp.com/refresh-interval: 10s
    vault.hashicorp.com/secret-name: abrakadabra
  labels:
    app.kubernetes.io/name: vault-secret-injector
    app.kubernetes.io/managed-by: kustomize
  name: vaultsecret-sample
spec:
  stringData:
    secret-key: secret/data/myapp/config#password
