apiVersion: vaultsecret.cfy.cz/v1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: vault-secret-injector
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  credsType: static
  stringTemplate:
    conn1: "postgresql://{{ .username }}:{{ .password }}@db-host:5432/mydb"
    conn2: |
     <Context>
       <Resource
           name="jdbc/PostgresDS"
           auth="Container"
           type="javax.sql.DataSource"
           driverClassName="org.postgresql.Driver"
           url="jdbc:postgresql://db-host:5432/app_db"
           username="{{ .username }}"
           password="{{ .password }}"
           maxTotal="10"
           maxIdle="5"
           maxWaitMillis="10000"/>
     </Context> 