[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = webhook-service

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = vault-secret-injector-webhook-service.vault-secret-injector-system.svc
DNS.2 = vault-secret-injector-webhook-service.vault-secret-injector-system.svc.cluster.local