name: Unit testing for Go project
on:
  workflow_call:
    inputs:
      os:
        description: 'Runs on OS system'
        type: string
        required: false
        default: 'ubuntu-latest'
      go-version:
        description: 'Go version'
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  linting:
    runs-on: ${{ inputs.os }} 
    needs: detect-go
    strategy:
      matrix:
        module: ${{ fromJson(needs.detect-go.outputs.matrix) }}
  
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
      - name: golangci-lint
        run: |
          make lint

  testing:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}  
      - name: Run testing scenarios 
        run: |
          make setup-envtest
          echo "KUBEBUILDER_ASSETS=$(./bin/setup-envtest use 1.31 --bin-dir ./bin -p path)"
          make test 