name: CI pipeline - Develop

on:
  workflow_dispatch:
  push:
    branches:
      - feat/**
      - fix/**
  pull_request:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context (pretty)
        run: |
          echo '${{ toJson(github) }}' | jq .

  unit-tests:
    uses: ./.github/workflows/golang_unit-tests.yml

  build:
    needs:
      - unit-tests
    uses: ./.github/workflows/build.yml
    with:
      expired: true
    secrets:
      OCI_REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      OCI_REGISTRY_PASSWORD: ${{ secrets.QUAY_TOKEN }}

  

#  test:
#    needs: build
#    uses: ./.github/workflows/test.yml

#  release:
#    if: github.ref == 'refs/heads/main'
#    needs: test
#    uses: ./.github/workflows/release.yml