name: Build Develop

on:
  workflow_dispatch:
  push:
    branches:
      - feat/**
      - fix/**

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context (pretty)
        run: |
          echo '${{ toJson(github) }}' | jq .

  setup:
    runs-on: ubuntu-latest
    outputs:
      organization: ${{ steps.set-vars.outputs.organization }}
      repository_name: ${{ steps.set-vars.outputs.repository_name }}
      platforms: ${{ steps.set-platforms.outputs.platforms }}
    steps:
      - name: Set new variables
        id: set-vars
        run: |
          echo "organization=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "project_name=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "matrix_platforms=$(echo '${{ inputs.platforms }}' | jq -R 'split(",")' | jq -c)" >> $GITHUB_OUTPUT

  build:
    needs:
      - setup
    uses: ./.github/workflows/_build_docker_container.yml
    with:
      expired: true
      organization: ${{ needs.setup.outputs.organization }}
      project: ${{ needs.setup.outputs.project_name }}
    secrets:
      OCI_REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      OCI_REGISTRY_PASSWORD: ${{ secrets.QUAY_TOKEN }}